security:
    encoders:
        App\Entity\User: bcrypt

    # ...

    providers:
        user_db:
            entity: {class: App\Entity\User, property: username}

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: user_db
            pattern: ^/
            anonymous: true
            form_login:
                login_path: login
                check_path: login
                csrf_token_generator: security.csrf.token_manager
            logout:
                path: /logout
                target: /login

    access_control: